### PR TITLE
update exiftool to 11.30 (last production release)

### PR DESCRIPTION
**Pull request by MCMicS**

### CODE REVIEW

**Comment by ndtreviv** [comment]
I really want this merged. How do we make it happen?

**Comment by MCMicS** [comment]
Still waiting.
Or change the maintaner to other. But the current one is not responding

**Comment by ndtreviv** [comment]
@MCMicS How would you feel about taking this over and publishing your branch to npm as a module?

**Comment by MCMicS** [comment]
Sounds great

@z-vr @neojski Is there anyone to transfer this repo ownership

**Comment by neojski** [comment]
I'm not really involved in this project so, sadly, I can't help you with ownership transfer.

**Comment by MCMicS** [comment]
There is another project: https://github.com/photostructure/exiftool-vendored.js

maybe all switch to these
But I still look to update this project

**Comment by ndtreviv** [comment]
> Sounds great
> 
> @z-vr @neojski Is there anyone to transfer this repo ownership

I got in touch with github about how to progress an effectively dead repo.
They said that we can't take it over, but we can fork it, and they'll set the fork up to be a standalone repo.

@MCMicS If I were you, I'd just publish your repo to npm. I'll start using it! As I mentioned in another issue, exiftool-vendored is noticeably slower at extracting that this version. 🤷‍♂️

Up to you, fella. The power is yours 😉

**Comment by MCMicS** [comment]
This sound like an option.
Will try to do this

**Comment by MCMicS** [comment]
@ndtreviv You can try https://www.npmjs.com/package/@mcmics/dist-exiftool

I'm still fix the travis build

**Pull request closed without merging**
