### PR TITLE
update exiftool to 11.01 (last production release)

### PR DESCRIPTION
**Pull request by MCMicS**

### CODE REVIEW

**Comment by douglassllc** [comment]
Any possibility on getting this package update to the latest exiftools version 11.38?

**Comment by MCMicS** [comment]
it would be possible. I can do it this weekend. But the last Production release is  11.30

**Comment by douglassllc** [comment]
11.30 works great!  I was specifically needing a newer version that support HEIC better and 11.30 has the necessary support.  Thank you.

Additional request.  I like how you have packaged up exiftools.  I have begun a similar project [mp4box-static](https://github.com/douglassllc/mp4box-static) to provide the same concept for mp4box.  Can you point me in the direction of documentation that might show how you packaged exiftools?  Or if you could provide a high-level explanation on how you organize the optionalDependencies and platformDependentModules.  Any guidance would be appreciated.

Thanks again for maintaining/updating this package.

**Comment by MCMicS** [comment]
I'm Not the Main devloper of this Projekt. i only Do some Updates.
The maintainer is @Sobesednik

The Platform dependent is done with two separate projects (for win and Unix). 

U can See in source.I ask the project lead to grant maintain access for this project . But no answer yet. If no maintenance is possible I will maybe use my for to update to latest versions.

**Comment by MCMicS** [comment]
replaced with PR #8

**Review by douglassllc — COMMENTED** [review]
Looks good!

**Pull request closed without merging**
